/*
 * Copyright (C) 2011 Li Xi <pkuelelixi@gmail.com>
 */

#include <linux/module.h>
#include <mtfs_io.h>

const struct mtfs_io_operations mtfs_io_ops[] = {
	[MIOT_CREATE] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_create,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_LINK] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_link,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_UNLINK] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_unlink,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_MKDIR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_mkdir,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_RMDIR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_rmdir,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_MKNOD] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_mknod,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_RENAME] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist_rename,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_rename,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_SYMLINK] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_symlink,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_READLINK] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_readlink,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_PERMISSION] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_permission,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_READV] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = mtfs_io_lock_mlock,
		.mio_unlock     = mtfs_io_unlock_mlock,
		.mio_iter_init  = mtfs_io_iter_init_rw,
		.mio_iter_start = mtfs_io_iter_start_rw,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_WRITEV] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = mtfs_io_lock_mlock,
		.mio_unlock     = mtfs_io_unlock_mlock,
		.mio_iter_init  = mtfs_io_iter_init_rw,
		.mio_iter_start = mtfs_io_iter_start_rw,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_GETATTR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_getattr,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_SETATTR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_setattr,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_GETXATTR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_getxattr,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_SETXATTR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_setxattr,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_REMOVEXATTR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_removexattr,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_LISTXATTR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_listxattr,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_READDIR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_readdir,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_SETATTR] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_setattr,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_OPEN] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist_noupdate,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_open,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_IOCTL_WRITE] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_ioctl,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_IOCTL_READ] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_ioctl,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
	[MIOT_WRITEPAGE] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = mtfs_io_fini_oplist,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_writepage,
		.mio_iter_end   = mtfs_io_iter_end_oplist,
		.mio_iter_fini  = mtfs_io_iter_fini_write_ops,
	},
	[MIOT_READPAGE] = {
		.mio_init       = mtfs_io_init_oplist_flag,
		.mio_fini       = NULL,
		.mio_lock       = NULL,
		.mio_unlock     = NULL,
		.mio_iter_init  = NULL,
		.mio_iter_start = mtfs_io_iter_start_readpage,
		.mio_iter_end   = NULL,
		.mio_iter_fini  = mtfs_io_iter_fini_read_ops,
	},
};
EXPORT_SYMBOL(mtfs_io_ops);
