.TH hrfs 1 "2012 Feb 4" hrfs "user utilities"
.SH NAME
hrfs \- Hrfs utility to manage files in a hrfs filesystem
.SH SYNOPSIS
.br
.B hrfs
.br
.B hrfs check <mds|osts|servers>
.br
.B hrfs getstate [--quiet | -q] [--verbose | -v] <dir|file>
.br
.B hrfs setbranch [--quiet | -q] [--verbose | -v]\n"
        \fB[--branch | -b bindex] [--data | -d flag]"
        \fB[--attr | -a flag] [--xattr | -x flag]"
        \fB<dir|file>
.br
.B hrfs version
.br
.B hrfs help
.SH DESCRIPTION
.B hrfs
can be used to get the state of a file, modify the state of a file. 
.SH OPTIONS
The various options supported by hrfs are listed and explained below:
.TP
.B getstate 
Get the state of a file
.TP
.B setbranch
Set the state of a file
.TP
.B help 
Provides brief help on the various arguments
.TP
.B exit/quit 
Quit the interactive hrfs session
.SH EXAMPLES
.TP
.B $ hrfs getstate /mnt/hrfs/file1
This gets the information of file.
.TP
.B $ hrfs setbranch -b 0 -d 1 /mnt/hrfs/file1
This signs the branch[0] of file /mnt/hrfs/file1 to be data-bad.
.SH BUGS
Report bugs using http://code.google.com/p/hrfs.
.SH AUTHOR
The hrfs command is part of the hrfs filesystem. Contact http://code.google.com/p/hrfs
Li Xi <pkuelelixi@gmail.com>
.SH SEE ALSO
.BR hrfsctl (8),
